
insert into roles (name, description) values ('login', 'Login');
insert into roles (name, description) values ('data', 'Data Entry');
insert into roles (name, description) values ('analysis', 'Data Analysis');
insert into roles (name, description) values ('reports', 'Reporting');
insert into roles (name, description) values ('management', 'Project Management');
insert into roles (name, description) values ('admin', 'Site and Operator Configuration');
insert into roles (name, description) values ('users', 'User Management');
insert into roles (name, description) values ('barcodes', 'Barcode Management');
insert into roles (name, description) values ('invoices', 'Invoice Management');
insert into roles (name, description) values ('tolerances', 'Accuracy and Tolerance Management');

-- users

insert into users (id, name, username, password) values(1, 'SGS', 'sgs', md5('5gSu8z_'));

-- roles for users

insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('login'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('data'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('analysis'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('reports'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('management'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('admin'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('users'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('barcodes'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('invoices'));
insert into roles_users (user_id, role_id) values (lookup_user_id('sgs'), lookup_role_id('tolerances'));

-- species

insert into species (code,class,botanic_name,trade_name,fob_price) values('AFRO','C','Afrosersalisia afzelii','Akuedao',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('AFZ','A','Afzelia spp (bella africana)','Doussie (Afzelia Apa)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ALB','C','Albizzia zygia','Zygia',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ALS','C','Alstonia boonei','Emien',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('AMP','C','Amphimas pterocarpoides','Lati (Bokango)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ANH','C','Anthonotha fragrans','Anthonotha (Kibokoko)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ANI','A','Anigeria robusta','Aningre (Annegre)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ANO','B','Anopyxis klaineana','Kokoti',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ANT','B','Antiaris africana','Ako',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ANTH','C','Anthcliesta nobilis','Cabbage Tree',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ARA','C','Araliopsis tabouensis','Araliopsis (Grenian)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('AUB','C','Aubrevillea platycarpa','Biethi',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BEI','C','Beilschmiedia mannii','Kanda (Tawa)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BER','C','Berlinia confusa','Pocouli (Ebiara)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BOM','B','Bombax buonopozense','Bombax',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BRA','A','Brachystegia leonensis','Naga',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BRI','C','Bridelia grandis','Doandoh',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('BUS','C','Bussea occidentalis','Samanta',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CAL','C','Calpocalyz aubrevillei','Badio (Calpocalz)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CAN','A','Canarium schweinfurthii','Aiele',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CEI','A','Ceiba pentandra','Ceiba (Fromager',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CEL','C','Celtis spp (aldolfi-friederiei)','Celtis (Lokenfi)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CHI','A','Chidlowia sanguinea','Bala',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CHL','A','Chlorophora','Iroko (Odum Kambala)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CHR','B','Chrysophyllum spp','Akatio (Longui)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('COM','C','Combretodendron macrocarpum','Abale',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('COP','C','Copaifera salikounda','Etimoe',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('COU','C','Coula edulis','Coula',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CRY','C','Cryptosepalum tetraphyllum','African Pine',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('CYN','B','Cynometra ananta','Apome',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DAC','C','Dacryodes klaineana','Monkey plum',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DAN','B','Daniella thurifera','Faro',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DIA','C','Dialium aubrevillei','kropio (Eyoum)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DID','B','Didelotia idea','Bondu',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DIO','C','Diospyros sanzaminika','Ebony',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('DIS','A','Distemonanthus benthamianus','Movingui',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ENTA','A','Entandrophragma angolense','Tiama (Edinam)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ENTC','A','Entandrophragma candollei','Kosipo (Abourd Kro)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ENTCY','A','Entandrophragma cylindricum','Sapele (Sapelle Aboudikro)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ENTU','A','Entandrophragma utile','Sipo (Utile)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ERY','B','Erythrophleum ivorensis','Tali (Sassawood)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ERYM','C','Erythroxylum mannii','Landa',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('FAG','C','Fagara macrophylla Fagara','Olondu',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('FUN','C','Funtumia elastica','Funtumia (Mutundu)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('GIL','A','Gilbertiodendron preussii','Limbali',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('GLU','C','Gluema ivoransis','Adiepingoa',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('GUA','A','Guarea cedrata','Bosse',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('GUI','A','Guibourtia ehie','Amazakoue (Bubinga)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('HAL','A','Hallea ciliata','Abura (Bahia)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('HAN','C','Hannoa klaineana','Hannoa (Effeu)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('HAP','B','Haplormosia macrophylla','Black gum (Idewa)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('IRV','C','Irvingia Gabonensis','Irvingia',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('KHA','A','Khaya anthotheca','Khaya (Acajou blanc)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('KHI','A','Khaya ivorensis','Khaya (Acajou d Afrique)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('KLA','C','Klainedoxa gabonensis','Klainodoxa (Eveuss)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('LOP','A','Lophira alata','Ekki  (Azobe)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('LOV','A','Lovoa trichilioides','Lovoa (Dibetou)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('MAM','B','Mammea africana','Mammea (Oboto)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('MAN','B','Mansonia altissima','Mansonia (Bete)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('MANI','C','Manilkara obovata','Duka (false Makore)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('MON','C','Monopetalanthus compactus','Ekop',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('MUS','C','Musanga cecropioides','African corkwood',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('NAU','A','Nauclea diderrichii','Kusia (Bilinga Opepe)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('NES','B','Nesogordonia papaverifera','Danta (Kotibe)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('NEW','C','Newtonia aubrevillei','Pellegrin',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('OLD','B','Oldfieldia africana','Oldfieldia (Dantoue)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('ONG','C','Ongokea gore','Angueuk (Kuwi)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PAC','C','Pachystela brevipes','Bokulolo',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PAK','C','Parkia bicolor','Parkia (Lo)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PAR','C','Parinari excelsa','Parinari (Songue)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PEN','C','Pentadesma butyracea','Timber-lacewood',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PENT','C','Pentaclethra macrophylla','Oil-bean tree',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PER','B','Pericopsis elata','Afromosia',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PIP','A','Piptadeniastrum africanum','Dahoma',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PTE','B','Pterygota macrocarpa','Koto (Ake)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('PYC','B','Pycnanthus africanus','Ilomba',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('RHO','B','Rhodoguaphalon brevicuape','Alone (Kondrotti)',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('RIC','C','Ricinondendron heudelotii','African Oil tree',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SAB','C','Sabicea species','Abobonkahyire',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SAC','B','Sacoglottis gabonensis','Ozouga',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SAM','C','Samanea dinklagai','Monkey Pod',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SAN','C','Sanseviera liberica','Africana Hemp',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('STR','C','Strombosia glaucescens','Afina',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SYM','C','Symphonia globulifera','Symphonia',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('SYN','C','Synsepalum dulcificum','Sweet Berry',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TAR','A','Heritiera utilis','Niangon (Whismore)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TEI','A','Terminalia ivorensis','Framire (Baji Emire)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TES','A','Terminalia superba','Frake (Limba Afara)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TET','A','Tetraberlinia tubmaniana','Tetra (Sikon)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TIE','A','Tieghemella heckelii','Makore (Baku Douka)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TRI','A','Triplochiton scleroxylon','Obeche (SambaWawa)',3);
insert into species (code,class,botanic_name,trade_name,fob_price) values('TUR','B','Turraeanthus africanus','Avodire',2);
insert into species (code,class,botanic_name,trade_name,fob_price) values('UAP','C','Uapaca guinensis','Uapaca (Rikio)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('UNK','C','Unknown','Unknown',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('XYL','C','Xylia evansii','Dan (Mano)',1);
insert into species (code,class,botanic_name,trade_name,fob_price) values('XYLO','C','Xylopia aethiopica','Guinea Papper Tree (Okala)',1);


-- updates for fob price

update species set fob_price = 170 where code = 'AFRO';
update species set fob_price = 260 where code = 'AFZ';
update species set fob_price = 170 where code = 'ALB';
update species set fob_price = 170 where code = 'ALS';
update species set fob_price = 170 where code = 'AMP';
update species set fob_price = 170 where code = 'ANH';
update species set fob_price = 170 where code = 'ANI';
update species set fob_price = 170 where code = 'ANO';
update species set fob_price = 170 where code = 'ANT';
update species set fob_price = 170 where code = 'ANTH';
update species set fob_price = 170 where code = 'ARA';
update species set fob_price = 170 where code = 'AUB';
update species set fob_price = 170 where code = 'BEI';
update species set fob_price = 170 where code = 'BER';
update species set fob_price = 190 where code = 'BOM';
update species set fob_price = 170 where code = 'BRA';
update species set fob_price = 170 where code = 'BRI';
update species set fob_price = 170 where code = 'BUS';
update species set fob_price = 170 where code = 'CAL';
update species set fob_price = 170 where code = 'CAN';
update species set fob_price = 170 where code = 'CEI';
update species set fob_price = 170 where code = 'CEL';
update species set fob_price = 170 where code = 'CHI';
update species set fob_price = 250 where code = 'CHL';
update species set fob_price = 170 where code = 'CHR';
update species set fob_price = 170 where code = 'COM';
update species set fob_price = 170 where code = 'COP';
update species set fob_price = 170 where code = 'COU';
update species set fob_price = 170 where code = 'CRY';
update species set fob_price = 150 where code = 'CYN';
update species set fob_price = 170 where code = 'DAC';
update species set fob_price = 180 where code = 'DAN';
update species set fob_price = 170 where code = 'DIA';
update species set fob_price = 170 where code = 'DID';
update species set fob_price = 170 where code = 'DIO';
update species set fob_price = 170 where code = 'DIS';
update species set fob_price = 230 where code = 'ENTA';
update species set fob_price = 170 where code = 'ENTC';
update species set fob_price = 170 where code = 'ENTCY';
update species set fob_price = 170 where code = 'ENTU';
update species set fob_price = 270 where code = 'ERY';
update species set fob_price = 170 where code = 'ERYM';
update species set fob_price = 170 where code = 'FAG';
update species set fob_price = 170 where code = 'FUN';
update species set fob_price = 170 where code = 'GIL';
update species set fob_price = 170 where code = 'GLU';
update species set fob_price = 170 where code = 'GUA';
update species set fob_price = 170 where code = 'GUI';
update species set fob_price = 170 where code = 'HAL';
update species set fob_price = 170 where code = 'HAN';
update species set fob_price = 170 where code = 'HAP';
update species set fob_price = 170 where code = 'IRV';
update species set fob_price = 170 where code = 'KHA';
update species set fob_price = 170 where code = 'KHI';
update species set fob_price = 170 where code = 'KLA';
update species set fob_price = 250 where code = 'LOP';
update species set fob_price = 180 where code = 'LOV';
update species set fob_price = 170 where code = 'MAM';
update species set fob_price = 170 where code = 'MAN';
update species set fob_price = 190 where code = 'MANI';
update species set fob_price = 170 where code = 'MON';
update species set fob_price = 170 where code = 'MUS';
update species set fob_price = 170 where code = 'NAU';
update species set fob_price = 170 where code = 'NES';
update species set fob_price = 170 where code = 'NEW';
update species set fob_price = 170 where code = 'OLD';
update species set fob_price = 170 where code = 'ONG';
update species set fob_price = 170 where code = 'PAC';
update species set fob_price = 170 where code = 'PAK';
update species set fob_price = 170 where code = 'PAR';
update species set fob_price = 170 where code = 'PEN';
update species set fob_price = 170 where code = 'PENT';
update species set fob_price = 170 where code = 'PER';
update species set fob_price = 190 where code = 'PIP';
update species set fob_price = 170 where code = 'PTE';
update species set fob_price = 170 where code = 'PYC';
update species set fob_price = 170 where code = 'RHO';
update species set fob_price = 170 where code = 'RIC';
update species set fob_price = 170 where code = 'SAB';
update species set fob_price = 170 where code = 'SAC';
update species set fob_price = 170 where code = 'SAM';
update species set fob_price = 170 where code = 'SAN';
update species set fob_price = 170 where code = 'STR';
update species set fob_price = 170 where code = 'SYM';
update species set fob_price = 170 where code = 'SYN';
update species set fob_price = 280 where code = 'TAR';
update species set fob_price = 203 where code = 'TEI';
update species set fob_price = 170 where code = 'TES';
update species set fob_price = 190 where code = 'TET';
update species set fob_price = 170 where code = 'TIE';
update species set fob_price = 170 where code = 'TRI';
update species set fob_price = 170 where code = 'TUR';
update species set fob_price = 170 where code = 'UAP';
update species set fob_price = 170 where code = 'UNK';
update species set fob_price = 170 where code = 'XYL';
update species set fob_price = 170 where code = 'XYLO';


-- tolerances

insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('TDF','is_matching_survey_line',2,20);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('TDF','is_matching_diameter',5,40);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('TDF','is_matching_length',2,10);

insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('LDF','is_matching_diameter',5,30);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('LDF','is_matching_length',0.5,2);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('LDF','is_matching_volume',0.2,2);

insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('SPECS','is_matching_diameter',5,30);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('SPECS','is_matching_length',0.5,2);
insert into tolerances (form_type,"check",accuracy_range,tolerance_range) values ('SPECS','is_matching_volume',0.2,2);
