
-- FOB Price

alter table species add column fob_price_low d_money;
alter table species add column fob_price_high d_money;

alter table species add constraint species_fob_price_check check (not((fob_price_high is not null) and (fob_price_high < fob_price_low)));

-- FOB Price updates

update species set fob_price_high = 427, fob_price_low = 405 where code = 'AFZ';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ALS';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'AMP';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ANH';
update species set fob_price_high = 207, fob_price_low = 196 where code = 'ANI';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'ANO';
update species set fob_price_high = 114, fob_price_low = 108 where code = 'ANT';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ARA';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'BEI';
update species set fob_price_high = 159, fob_price_low = 150 where code = 'BER';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'BOM';
update species set fob_price_high = 180, fob_price_low = 170 where code = 'BRA';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'CAL';
update species set fob_price_high = 160, fob_price_low = 151 where code = 'CAN';
update species set fob_price_high = 131, fob_price_low = 124 where code = 'CEI';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'CEL';
update species set fob_price_high = 223, fob_price_low = 211 where code = 'CHL';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'CHR';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'COM';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'COP';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'CYN';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'DAN';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'DIA';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'DID';
update species set fob_price_high = 187, fob_price_low = 177 where code = 'DIS';
update species set fob_price_high = 159, fob_price_low = 151 where code = 'ENTA';
update species set fob_price_high = 188, fob_price_low = 178 where code = 'ENTC';
update species set fob_price_high = 262, fob_price_low = 248 where code = 'ENTCY';
update species set fob_price_high = 243, fob_price_low = 230 where code = 'ENTU';
update species set fob_price_high = 260, fob_price_low = 246 where code = 'ERY';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ERYM';
update species set fob_price_high = 153, fob_price_low = 144 where code = 'FAG';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'FUN';
update species set fob_price_high = 211, fob_price_low = 200 where code = 'GIL';
update species set fob_price_high = 175, fob_price_low = 166 where code = 'GUA';
update species set fob_price_high = 317, fob_price_low = 300 where code = 'GUI';
update species set fob_price_high = 194, fob_price_low = 183 where code = 'HAL';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'HAN';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'HAP';
update species set fob_price_high = 213, fob_price_low = 201 where code = 'KHA';
update species set fob_price_high = 224, fob_price_low = 212 where code = 'KHI';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'KLA';
update species set fob_price_high = 231, fob_price_low = 219 where code = 'LOP';
update species set fob_price_high = 187, fob_price_low = 177 where code = 'LOV';
update species set fob_price_high = 166, fob_price_low = 156 where code = 'MAM';
update species set fob_price_high = 190, fob_price_low = 179 where code = 'MAN';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'MANI';
update species set fob_price_high = 204, fob_price_low = 194 where code = 'NAU';
update species set fob_price_high = 213, fob_price_low = 201 where code = 'NES';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'OLD';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ONG';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'PAK';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'PAR';
update species set fob_price_high = 365, fob_price_low = 345 where code = 'PER';
update species set fob_price_high = 172, fob_price_low = 163 where code = 'PIP';
update species set fob_price_high = 155, fob_price_low = 146 where code = 'PTE';
update species set fob_price_high = 156, fob_price_low = 147 where code = 'PYC';
update species set fob_price_high = 146, fob_price_low = 138 where code = 'RHO';
update species set fob_price_high = 153, fob_price_low = 145 where code = 'SAC';
update species set fob_price_high = 266, fob_price_low = 252 where code = 'TAR';
update species set fob_price_high = 238, fob_price_low = 225 where code = 'TEI';
update species set fob_price_high = 179, fob_price_low = 169 where code = 'TES';
update species set fob_price_high = 175, fob_price_low = 166 where code = 'TET';
update species set fob_price_high = 223, fob_price_low = 211 where code = 'TIE';
update species set fob_price_high = 188, fob_price_low = 178 where code = 'TRI';
update species set fob_price_high = 156, fob_price_low = 147 where code = 'TUR';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'UAP';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'UNK';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'XYL';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'XYLO';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'AFRO';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ALB';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'ANTH';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'AUB';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'BRI';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'BUS';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'COU';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'CRY';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'DAC';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'DIO';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'GLU';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'IRV';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'MON';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'MUS';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'NEW';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'PAC';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'PEN';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'PENT';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'RIC';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'SAB';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'SAM';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'SAN';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'STR';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'SYM';
update species set fob_price_high = 145, fob_price_low = 136 where code = 'SYN';
