
-- users

insert into users (user_id,username,access_level) values (1,'sgs','A');

-- species

insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (1,'AFRO','C','Afrosersalisia afzelii','Akuedao',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (2,'AFZ','A','Afzelia spp (bella africana)','Doussie (Afzelia Apa)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (3,'ALB','C','Albizzia zygia','Zygia',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (4,'ALS','C','Alstonia boonei','Emien',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (5,'AMP','C','Amphimas pterocarpoides','Lati (Bokango)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (6,'ANH','C','Anthonotha fragrans','Anthonotha (Kibokoko)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (7,'ANI','A','Anigeria robusta','Aningre (Annegre)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (8,'ANO','B','Anopyxis klaineana','Kokoti',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (9,'ANT','B','Antiaris africana','Ako',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (10,'ANTH','C','Anthcliesta nobilis','Cabbage Tree',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (11,'ARA','C','Araliopsis tabouensis','Araliopsis (Grenian)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (12,'AUB','C','Aubrevillea platycarpa','Biethi',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (13,'BEI','C','Beilschmiedia mannii','Kanda (Tawa)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (14,'BER','C','Berlinia confusa','Pocouli (Ebiara)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (15,'BOM','B','Bombax buonopozense','Bombax',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (16,'BRA','A','Brachystegia leonensis','Naga',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (17,'BRI','C','Bridelia grandis','Doandoh',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (18,'BUS','C','Bussea occidentalis','Samanta',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (19,'CAL','C','Calpocalyz aubrevillei','Badio (Calpocalz)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (20,'CAN','A','Canarium schweinfurthii','Aiele',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (21,'CEI','A','Ceiba pentandra','Ceiba (Fromager',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (22,'CEL','C','Celtis spp (aldolfi-friederiei)','Celtis (Lokenfi)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (23,'CHI','A','Chidlowia sanguinea','Bala',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (24,'CHL','A','Chlorophora','Iroko (Odum Kambala)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (25,'CHR','B','Chrysophyllum spp','Akatio (Longui)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (26,'COM','C','Combretodendron macrocarpum','Abale',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (27,'COP','C','Copaifera salikounda','Etimoe',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (28,'COU','C','Coula edulis','Coula',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (29,'CRY','C','Cryptosepalum tetraphyllum','African Pine',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (30,'CYN','B','Cynometra ananta','Apome',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (31,'DAC','C','Dacryodes klaineana','Monkey plum',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (32,'DAN','B','Daniella thurifera','Faro',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (33,'DIA','C','Dialium aubrevillei','kropio (Eyoum)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (34,'DID','B','Didelotia idea','Bondu',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (35,'DIO','C','Diospyros sanzaminika','Ebony',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (36,'DIS','A','Distemonanthus benthamianus','Movingui',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (37,'ENTA','A','Entandrophragma angolense','Tiama (Edinam)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (38,'ENTC','A','Entandrophragma candollei','Kosipo (Abourd Kro)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (39,'ENTCY','A','Entandrophragma cylindricum','Sapele (Sapelle Aboudikro)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (40,'ENTU','A','Entandrophragma utile','Sipo (Utile)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (41,'ERY','B','Erythrophleum ivorensis','Tali (Sassawood)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (42,'ERYM','C','Erythroxylum mannii','Landa',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (43,'FAG','C','Fagara macrophylla Fagara','Olondu',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (44,'FUN','C','Funtumia elastica','Funtumia (Mutundu)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (45,'GIL','A','Gilbertiodendron preussii','Limbali',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (46,'GLU','C','Gluema ivoransis','Adiepingoa',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (47,'GUA','A','Guarea cedrata','Bosse',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (48,'GUI','A','Guibourtia ehie','Amazakoue (Bubinga)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (49,'HAL','A','Hallea ciliata','Abura (Bahia)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (50,'HAN','C','Hannoa klaineana','Hannoa (Effeu)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (51,'HAP','B','Haplormosia macrophylla','Black gum (Idewa)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (52,'IRV','C','Irvingia Gabonensis','Irvingia',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (53,'KHA','A','Khaya anthotheca','Khaya (Acajou blanc)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (54,'KHI','A','Khaya ivorensis','Khaya (Acajou d Afrique)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (55,'KLA','C','Klainedoxa gabonensis','Klainodoxa (Eveuss)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (56,'LOP','A','Lophira alata','Ekki  (Azobe)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (57,'LOV','A','Lovoa trichilioides','Lovoa (Dibetou)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (58,'MAM','B','Mammea africana','Mammea (Oboto)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (59,'MAN','B','Mansonia altissima','Mansonia (Bete)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (60,'MANI','C','Manilkara obovata','Duka (false Makore)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (61,'MON','C','Monopetalanthus compactus','Ekop',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (62,'MUS','C','Musanga cecropioides','African corkwood',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (63,'NAU','A','Nauclea diderrichii','Kusia (Bilinga Opepe)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (64,'NES','B','Nesogordonia papaverifera','Danta (Kotibe)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (65,'NEW','C','Newtonia aubrevillei','Pellegrin',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (66,'OLD','B','Oldfieldia africana','Oldfieldia (Dantoue)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (67,'ONG','C','Ongokea gore','Angueuk (Kuwi)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (68,'PAC','C','Pachystela brevipes','Bokulolo',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (69,'PAK','C','Parkia bicolor','Parkia (Lo)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (70,'PAR','C','Parinari excelsa','Parinari (Songue)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (71,'PEN','C','Pentadesma butyracea','Timber-lacewood',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (72,'PENT','C','Pentaclethra macrophylla','Oil-bean tree',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (73,'PER','B','Pericopsis elata','Afromosia',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (74,'PIP','A','Piptadeniastrum africanum','Dahoma',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (75,'PTE','B','Pterygota macrocarpa','Koto (Ake)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (76,'PYC','B','Pycnanthus africanus','Ilomba',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (77,'RHO','B','Rhodoguaphalon brevicuape','Alone (Kondrotti)',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (78,'RIC','C','Ricinondendron heudelotii','African Oil tree',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (79,'SAB','C','Sabicea species','Abobonkahyire',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (80,'SAC','B','Sacoglottis gabonensis','Ozouga',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (81,'SAM','C','Samanea dinklagai','Monkey Pod',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (82,'SAN','C','Sanseviera liberica','Africana Hemp',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (83,'STR','C','Strombosia glaucescens','Afina',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (84,'SYM','C','Symphonia globulifera','Symphonia',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (85,'SYN','C','Synsepalum dulcificum','Sweet Berry',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (86,'TAR','A','Heritiera utilis','Niangon (Whismore)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (87,'TEI','A','Terminalia ivorensis','Framire (Baji Emire)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (88,'TES','A','Terminalia superba','Frake (Limba Afara)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (89,'TET','A','Tetraberlinia tubmaniana','Tetra (Sikon)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (90,'TIE','A','Tieghemella heckelii','Makore (Baku Douka)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (91,'TRI','A','Triplochiton scleroxylon','Obeche (SambaWawa)',3);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (92,'TUR','B','Turraeanthus africanus','Avodire',2);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (93,'UAP','C','Uapaca guinensis','Uapaca (Rikio)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (94,'UNK','C','Unknown','Unknown',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (95,'XYL','C','Xylia evansii','Dan (Mano)',1);
insert into species (species_id,code,class,botanic_name,trade_name,fob_price) values (96,'XYLO','C','Xylopia aethiopica','Guinea Papper Tree (Okala)',1);
